version: 2.0

jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3072m -Djava.util.concurrent.ForkJoinPool.common.parallelism=2
      TERM: dumb
    steps:
      - run:
          name: Update SDK
          command: |
            mkdir "$ANDROID_HOME/licenses" || true
            echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
            echo "84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
            sdkmanager "platform-tools" "platforms;android-28"
      - checkout
      - run:
          name: Submodule Init
          command: git submodule init
      - run:
          name: Submodule Update
          command: git submodule update

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies --no-daemon
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Assemble APKs
          command: |
                        if [ "${CIRCLE_BRANCH}" == "develop" ]; then
                          ./gradlew app:assembleDebug --no-daemon;
                        elif [ "${CIRCLE_BRANCH}" == "uat" ]; then
                          ./gradlew app:assembleUat --no-daemon;
                        else
                          ./gradlew app:assembleDebug --no-daemon;
                        fi

      - store_artifacts:
          path: app/build/outputs/apk
          destination: apks

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - store_test_results:
          path: app/build/test-results

